### ISSUE TITLE
Wrong apiurl for cli scanner

### ISSUE THREAD

**Issue by spimmer** [jasonumiker-sysdig/sysdig-aws-workshop-instructions#1]
The provided API URL in the folllowing line is incorrect:
https://github.com/jasonumiker-sysdig/sysdig-aws-workshop-instructions/blob/e217e17a1bc35cdce2f33a3595d4fc79ceb735d8/Readme.md?plain=1#L348

According to https://docs.sysdig.com/en/docs/administration/saas-regions-and-ip-ranges/#european-union it should be:
`./sysdig-cli-scanner -a eu1.app.sysdig.com logstash:7.16.1`

**Comment by jasonumiker-sysdig** [comment]
There is a branch for each region for the workshop that localises the instructions for that region. If you are in Europe you should pick the CDG or FRA branch.
